# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_31; TYPE=coverage; PHPUNIT=4.8.*
      php: 7.1
    - env: DB=mysql; MW=master; PHPUNIT=4.8.*
      php: 7.2
    - env: DB=sqlite; MW=REL1_31; SITELANG=ja; PHPUNIT=4.8.*
      php: 5.6

install:
  - composer self-update
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-approved-revs.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

cache:
  directories:
    - $HOME/.composer/cache
